### Register user/admin
POST {{url}}/auth/register
Content-Type: application/json

{
  "user_email": "admin",
  "password": "admin",
  "role": "admin"
}

> {% client.global.set("token", response.body.json.token); %}

### Register user/user
POST {{url}}/auth/register
Content-Type: application/json

{
  "user_email": "user",
  "password": "user",
  "role": "user"
}

### Register user_manager/manager
POST {{url}}/auth/register
Content-Type: application/json

{
  "user_email": "manager",
  "password": "manager",
  "role": "manager"
}

> {% client.global.set("token", response.body.token); %}

### Login as admin
POST {{url}}/auth/login
Content-Type: application/json

{
  "user_email": "admin",
  "password": "admin"
}

> {% client.global.set("token", response.body.token); %}

### Login as jslam
POST {{url}}/auth/login
Content-Type: application/json

{
  "user_email": "jslam@oulund.dk",
  "password": "hej1234"
}
> {%
    client.global.set("token", response.body.token);
    client.global.set("user_email", response.body.user_id);
%}

### Login as user user
POST {{url}}/auth/login
Content-Type: application/json

{
  "user_email": "user",
  "password": "user"
}
> {%
    client.global.set("token", response.body.token);
    client.global.set("user_email", response.body.user_id);
%}


### Login as manager
POST {{url}}/auth/login
Content-Type: application/json

{
  "user_email": "manager",
  "password": "manager"
}

> {% client.global.set("token", response.body.token); %}

###