### GET jslam NoteGroups
GET {{url}}/users/jslam@oulund.dk/note_groups
authorization: Bearer {{token}}


### Post NoteGroups for jslam

POST {{url}}/users/jslam@oulund.dk/note_groups
authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "ToDo"
}


### DELETE NoteGroup for jslam
DELETE {{url}}/users/jslam@oulund.dk/note_groups/3
authorization: Bearer {{token}}


### POST Create Note for notegroup jslam
POST {{url}}/users/jslam@oulund.dk/note_groups/1/notes
authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "Note 2 content"
}

### DELETE Note for notegroup jslam
DELETE {{url}}/users/jslam@oulund.dk/note_groups/1/notes/2
authorization: Bearer {{token}}


### UPDATE Note for notegroup jslam
PUT {{url}}/users/jslam@oulund.dk/note_groups/1/notes/4
authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "Note 2 content",
    "dueDate": "2020-12-12",
    "status": "DOING"
}



### GET User NoteGroups
GET {{url}}/users/user/note_groups
authorization: Bearer {{token}}

### Post NoteGroups for user

POST {{url}}/users/user/note_groups
authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "ToDo"
}